<div class="container">
    <h1 class="my-3">Přehled oscarů za nejlepší mužskou a ženskou hlavní roli</h1>

    <form action="/upload" method="post" enctype="multipart/form-data">
        <div class="d-flex flex-column">
            <div class="col-md-6 mx-auto mt-4">
                <div class="mb-3">
                    <label for="csvMale" class="form-label">Muži <span class="text-danger">*</span> </label>
                    <input class="form-control" type="file" id="csvMale" name="male" accept=".csv" required>
                </div>
                <div class="mb-3">
                    <label for="csvFemale" class="form-label">Ženy <span class="text-danger">*</span></label>
                    <input class="form-control" type="file" id="csvFemale" name="female" accept=".csv" required>
                </div>

                <button type="submit" class="btn btn-lg btn-primary d-block mt-5 mx-auto">Zpracovat</button>
            </div>
        </div>
    </form>
</div>